version: '3'

services:
  mysql:
    build: ./db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: nimad
    networks:
      - bao-net
    volumes:
      - db-data:/var/lib/mysql

  back:
    build: ./bao_api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - bao-net

volumes:
  db-data:

networks:
  bao-net:
