version: '3'

services:
  mysql:
    build: ./db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: nimad
    networks:
      - bao-net
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/mysql

  back:
    build: ./bao_api
    ports:
      - "8080:8080"
    networks:
      - bao-net
    depends_on:
      - mysql

volumes:
  db-data:

networks:
  bao-net:
